"""Cascade delete added for store address

Revision ID: 13b00503605a
Revises: 7053588ec912
Create Date: 2025-06-01 15:31:26.506100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13b00503605a'
down_revision: Union[str, None] = '7053588ec912'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('store_address_uuid_fkey', 'store', type_='foreignkey')
    op.create_foreign_key(None, 'store', 'address', ['address_uuid'], ['uuid'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'store', type_='foreignkey')
    op.create_foreign_key('store_address_uuid_fkey', 'store', 'address', ['address_uuid'], ['uuid'])
    # ### end Alembic commands ###
