"""VerificationStatus added on user

Revision ID: 62f1a8ae9eb9
Revises: 1aa38dfd1c95
Create Date: 2025-04-26 20:34:01.691277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62f1a8ae9eb9'
down_revision: Union[str, None] = '1aa38dfd1c95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    user_verification_status = sa.Enum(
    'PENDING', 'EMAIL', 'PHONE', 'EMAIL_AND_PHONE',
    name='userverificationstatus'
    )
    user_verification_status.create(op.get_bind())
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('verification_status', sa.Enum('PENDING', 'EMAIL', 'PHONE', 'EMAIL_AND_PHONE', name='userverificationstatus'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'verification_status')
    # ### end Alembic commands ###
