"""Cnpj switched to a non unique field

Revision ID: 7053588ec912
Revises: e2e4c52db824
Create Date: 2025-06-01 01:08:50.507232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7053588ec912'
down_revision: Union[str, None] = 'e2e4c52db824'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('store_cnpj_key', 'store', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('store_cnpj_key', 'store', ['cnpj'])
    # ### end Alembic commands ###
