"""Opening date, size, legal nature, cnae code and branch classification added for store

Revision ID: d7e1e13e6f17
Revises: bd72317e7e24
Create Date: 2025-04-27 14:59:57.618688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7e1e13e6f17'
down_revision: Union[str, None] = 'bd72317e7e24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store', sa.Column('opening_date', sa.Date(), nullable=False))
    op.add_column('store', sa.Column('size', sa.String(length=20), nullable=False))
    op.add_column('store', sa.Column('legal_nature', sa.String(length=20), nullable=False))
    op.add_column('store', sa.Column('cnae_code', sa.String(length=20), nullable=False))
    op.add_column('store', sa.Column('branch_classification', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store', 'branch_classification')
    op.drop_column('store', 'cnae_code')
    op.drop_column('store', 'legal_nature')
    op.drop_column('store', 'size')
    op.drop_column('store', 'opening_date')
    # ### end Alembic commands ###
