"""Minimum count added to demand

Revision ID: e2e4c52db824
Revises: 132c7c86d1f5
Create Date: 2025-05-12 23:03:38.496345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2e4c52db824'
down_revision: Union[str, None] = '132c7c86d1f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'demand',
        sa.Column('minimum_count', sa.Integer(), nullable=False, server_default='1')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('demand', 'minimum_count')
    # ### end Alembic commands ###
