from enum import Enum


class ProductType(Enum):
    BEEF = 'BEEF'
    WHITE_MEAT = 'WHITE_MEAT'
    SEAWEED = 'SEAWEED'
    SPICE = 'SPICE'
    SEAFOOD = 'SEAFOOD'
    PROCESSED_MEAT = 'PROCESSED_MEAT'
    PRESERVED_MEAT = 'PRESERVED_MEAT'
    PRESERVED_PRODUCT = 'PRESERVED_PRODUCT'
    PORK = 'PORK'
    ROOT_VEGETABLE = 'ROOT_VEGETABLE'
    NUT = 'NUT'
    MUSHROOM = 'MUSHROOM'
    VEGETABLE = 'VEGETABLE'
    HERB = 'HERB'
    GRAIN = 'GRAIN'
    FRUIT = 'FRUIT'
    EGG = 'EGG'
    DAIRY = 'DAIRY'